name: Testing the code and deploying test report

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and gen report
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - run: |
          make cover
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git add index.html
          git commit -m "Publishing Test Report"
          git push -f origin gh-pages
